### ISSUE TITLE
Request Firmware update frequency

### ISSUE THREAD

**Issue by mrcheap1984** [drandyhaas/haasmesh#1]
I Just received my mesh devices today, setup was so easy.

I've noticed there is a firmware update button located in the monitor page.  I know we can perform a manual build but was wondering if there are plans to release updates via this path?

OpenWRT is currently on 19.07.7 with the devices on 19.07.4 and has there been any build attempts on 21.02  (currently at RC2) ?

Thanks again and you have done a great work with this mesh system.

**Comment by drandyhaas** [comment]
I have no specific plans for a firmware update right now. But as feedback is gathered and/or bugs are found, there may be some in the future.
