### ISSUE TITLE
HaasMeshWifi Kernel Incompatible with kmod-usb-storage?

### ISSUE THREAD

**Issue by BalooRJ1** [drandyhaas/haasmesh#10]
Hello,

I am attempting to install the kmod-usb-storage package on a Linksys/Belkin RT3200 Wifi 6 router that I purchased from HaasMeshWifi directly on eBay so I can plug in an external usb hard drive and use it as a samba share over the network. However, went attempting to install kmod-usb-storage, I get the following warning:

The installed version of package kernel is not compatible, require 5.15.129-1-0621103d062f438197d77996112997e7 while 5.10.58-1-190dd3742c395bb8535b2c9f79c5e8b5 is installed.

Would I need to recompile a custom haasmeshwifi kernel to install this package for my router?

**Comment by drandyhaas** [comment]
Yes, kernel modules need to be built at runtime.
I've built a new firmware with kmod-usb-storage included (hopefully), you can update through the haasmesh status page on your router at 192.168.2.1 for the rt3200 model.
LMK if it works please.

**Comment by BalooRJ1** [comment]
This works now, thanks so much!
