### ISSUE TITLE
Cant Update Scripts or Factory Reset

### ISSUE THREAD

**Issue by BalooRJ1** [drandyhaas/haasmesh#11]
Hello,

I have found an issue where I've accidentally removed the Mesh WiFi Band from the hub node when I attempted to change the name of the SSID for the 5ghz band only to differentiate it from the 2.4 GHz band I am attempting to factory reset the hub node to correct this issue. However, when I attempt to reset the hub node, I get this issue:

Do " /root/script/updatefirmware.sh " on each node

c-24-13-168-1.h:

foreachnodeparellel: still jobs
ssh: Could not resolve hostname c-24-13-168-1.h: Name does not resolve
foreachnodeparellel: done!

This same error "Name does not resolve" occurs for attempting to update the scripts from Github and update the firmware from Dropbox. Could you provide any assistance? Thanks so much.

**Comment by drandyhaas** [comment]
Huh, it must be something about the hostname you chose, c-24-13-168-1.h

You can also factory reset the nice manually by holding the reset button on it for 5+ seconds, while the node is on.

**Comment by BalooRJ1** [comment]
Thank you so much! Very glad the ability to factory reset using the device was there. I just purchased a second Belkin RT3200 from you to use as a mesh router extension point. Is there a way to differentiate the name of the 2.4ghz and the 5ghz bands?

**Comment by drandyhaas** [comment]
There are actually one 2.4 ghz and two 5 ghz bands on a triband device. You can change the names of each on this page
http://192.168.2.1/cgi-bin/luci/admin/network/wireless#
or Network / Wireless in the top menu. Just click Edit on any of the interfaces that are mode:Master, not the Mesh Point interface. In the pop up dialog, edit the ESSID name and then save and then apply.

**Comment by BalooRJ1** [comment]
Strange, that is what I did earlier and it caused the entire 5ghz radio to deactivate. Could it be a bug? Then when I renamed the 5ghz band the Mesh band completely disappeared. I'll have to retry at a later point to see if it was user error on my end. Thanks Dr. Haas.
