### ISSUE TITLE
LUCI GUI for some nodes have become corrupt...

### ISSUE THREAD

**Issue by iabhua** [drandyhaas/haasmesh#12]
This is probably a OpenWRT problem but ...
I have 6 mesh nodes:
5x EA8300
1x EW72

All but 2 EA8300 have recently become corrupt, somehow... and display:
***************************************************************************
/usr/lib/lua/luci/dispatcher.lua:1081: module 'luci.controller.myapp.haas_mesh_tab' not found:
	no field package.preload['luci.controller.myapp.haas_mesh_tab']
	no file './luci/controller/myapp/haas_mesh_tab.lua'
	no file '/usr/share/lua/luci/controller/myapp/haas_mesh_tab.lua'
	no file '/usr/share/lua/luci/controller/myapp/haas_mesh_tab/init.lua'
	no file '/usr/lib/lua/luci/controller/myapp/haas_mesh_tab.lua'
	no file '/usr/lib/lua/luci/controller/myapp/haas_mesh_tab/init.lua'
	no file './luci/controller/myapp/haas_mesh_tab.so'
	no file '/usr/lib/lua/luci/controller/myapp/haas_mesh_tab.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1081: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1192: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:694: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:795: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
***************************************************************************
I have physically restarted but they still come up with the above.

The Mesh is still working. It is only the LUCI interface that has problems.

Should I factory reset? Fix some other way?

**Comment by drandyhaas** [comment]
Never seen that. 
It happens when you go to what webpage? Just 192.168.2.3, for instance? Try from a different web browser on a different computer?

**Comment by iabhua** [comment]
Any web page from any browser. Something to do with Luci Ui

**Comment by drandyhaas** [comment]
Very weird. Did you attempt to upgrade them or something? These should only be upgraded using the Maxwell webpage. You might need to factory reset to restore, sorry.

**Comment by iabhua** [comment]
Dear Andy

No problem. I have actually only used the Maxwell page to do anything on them…

I haven’t tried to fix them… my main unit still shows the ui and the rest all are now inaccessible!? But still working somehow, so to date I haven’t tried to fix anything.

I thought that maybe you have seen this before but guess I’ll have to reset them before it spreads to my main one!

Thanks
Ian
Sent from my iPhone

On 10 Aug 2024, at 12:48, Andy ***@***.***> wrote:

﻿

Very weird. Did you attempt to upgrade them or something? These should only be upgraded using the Maxwell webpage. You might need to factory reset to restore, sorry.
