### ISSUE TITLE
Luma - can't connect, has said working of processes for over a year 

### ISSUE THREAD

**Issue by olstykke** [drandyhaas/haasmesh#13]
Of the four maxwell devices I have - the only LUMA has been giving me fits. It connects to the mesh, but you can't update or connect to the hub directly " Bad gateway process did not produce any response"

When I run either the dropbox or github updates I get this :

192.168.2.4:

foreachnodeparellel: still jobs
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:60V8VR/LlZM1vw9qVvtprFQw7pClQpFIng3Ng6NX5pE.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /root/.ssh/known_hosts:6
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
UpdateHostkeys is disabled because the host key is not trusted.
root@192.168.2.3: Permission denied (publickey,password).
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:ZU87MQDkxOD6r8yMBvaokTb0V/4FeX9Qh4ZBFVosuxI.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /root/.ssh/known_hosts:1
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
UpdateHostkeys is disabled because the host key is not trusted.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:wx1NbQUE8TC0bKLKTwLZXMGS9Ek4vVdcV1S2Jua4AEA.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /root/.ssh/known_hosts:5
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
UpdateHostkeys is disabled because the host key is not trusted.
Getting Linksys E8450 (or Belkin RT3200) firmware
root@192.168.2.4: Permission denied (publickey,password).

I have tried connecting via a lan wire - I have reset it ( via the pin hole reset button) multiple times and cannot get this behavior to change. 

The hub appears in the mesh routing. Ping and Mesh lights in the monitoring are green.

I will say the luma takes forever for the light to change to indicate its connected to the mesh. This is why I let it sit ( hoping it was just a slow cpu compiling its kernel).

The still jobs is what made me think it was still compiling something.

For the potential man in the middle attacks - Its been giving the same jobs processsing and potential man in the middle warnings since I purchased it.  

Would appreciate any help. My other units are beklins, I'm considering buying another belkin since the belkins seem to play nice with each other.

**Comment by drandyhaas** [comment]
Hmmm. Hard to say. Could be some firmware corruption. I'm happy to send you a new one if you dm me.
