### ISSUE TITLE
Full image for re-flashing router?

### ISSUE THREAD

**Issue by asmagill** [drandyhaas/haasmesh#3]
I was attempting to upgrade the firmware with a newer kernel so I could install OpenVPN (kmod_tun for the Archer C7 V2 requires a newer kernel than what's provided) and I've basically borked it... the thing is now stuck in a reboot loop every time I turn it on.

I've ben reading about reinstalling a full openwrt image by holding down the reset/wps button while turning the router on which then tries to poll a tftp server for the image, but the dropbox links in your scripts only seem to refer to the sysupgrade image and I think I need the full image. I'm planning to set up a tftp server when I have access to my windows machine tomorrow and am hoping you have the full image also in your drop box somewhere that I can grab it from... I've got the TP-Link Archer C7 v2 model, and I have the "openwrt-ath79-generic-tplink_archer-c7-v2-squashfs-sysupgrade.bin" file... what I think I need would likely be named something like "openwrt-ath79-generic-tplink_archer-c7-v2-squashfs-factory.bin" or similar.

Can this image be made available somewhere? Or is it, and I've just missed it?

If not, would using the stock 19.07.3 factory image and then upgrading with "openwrt-ath79-generic-tplink_archer-c7-v2-squashfs-sysupgrade.bin" work?

Thanks for any help or advice you can provide.

**Comment by drandyhaas** [comment]
This is the Maxwell factory image needed for fresh install on archer c7 v2 (via tftp or from the stock firmware)...
https://www.dropbox.com/s/h7l87bhgryqatf4/openwrt-ath79-generic-tplink_archer-c7-v2-squashfs-factory-us.bin?dl=0

**Comment by asmagill** [comment]
Thanks, that worked perfectly!

**Comment by asmagill** [comment]
Since this request is similar, figured I'd keep it in the same post...

This time, my archer c7-v2 was damaged by power issues (the one device not on a ups wouldn't you know!). I have a TPLink Archer C7-V5 from a previous network I used to manage and figured I'd use it as a replacement since I see that its listed as being supported; however I need the initial factory image for a fresh install. Could you post that to dropbox as well?

Again, this time it's the Archer C7 V5 squashfs-factory image I need. Thanks!

**Comment by drandyhaas** [comment]
https://www.dropbox.com/s/aisdwzw6nhlyxnd/openwrt-ath79-generic-tplink_archer-c7-v5-squashfs-factory.bin?dl=0
