### ISSUE TITLE
Impossible to integrate into existing LAN with DHCP?

### ISSUE THREAD

**Issue by gisforgirard** [drandyhaas/haasmesh#4]
Because there is no way to edit the mesh network settings in luci there is no way to set up DHCP only on the mesh0 interface and not the LAN, also there is no way to set up the mesh network so that wifi clients can be seen by the existing LAN clients because the firewall is assuming it's connected to the Internet, and not to a LAN. Is there anything that can be done about this?

If I disable the DHCP server on the mesh nodes, then the nodes won't associate properly. Everything is hardcoded to the 192.168.2.x addresses. Do I connect the Internet straight into one of the mesh nodes, and reconfigure my entire network? I'm not sure what to do and I keep messing everything up trying to come up with some configuration that works. I have been trying to figure this out for weeks and still have no solution. I'm thinking about giving up and throwing it all away, I don't know what else to do.

**Comment by drandyhaas** [comment]
I'm not clear what you're trying to do exactly. You have Maxwell nodes, one of which is the hub, plugged into some other lan switch, which is running in a subnet other than 192.168.2.x?
And you want clients on that other subnet to have full access to the mesh on 192.168.2.x?
I don't see why you would want to mess with DHCP.

**Comment by gisforgirard** [comment]
If I have an existing network and want to include the mesh nodes, they are
on their own subnet, which is also the same subnet that the wifi clients
are on which connect to the HaasMeshWifi - 192.168.2.x, which, if I try to
connect to those clients connected to the wifi from a client on my LAN, the
firewall won't allow it because it assumes it's connected to the Internet
and not a LAN. The wifi clients would be able to connect to the existing
LAN but not the other way around.

**Comment by drandyhaas** [comment]
You could just disable the firewall on the hub node.

**Comment by gisforgirard** [comment]
And bridge the wifi interfaces with the LAN? Or do I have the wrong idea entirely?

**Comment by drandyhaas** [comment]
Maxwell wifi is already bridged to the Maxwell lan.

**Comment by gisforgirard** [comment]
When I disconnect the WAN port and plug the ethernet cable into the LAN port it stops responding to the IP that was statically assigned to the LAN interface?

**Comment by gisforgirard** [comment]
cool, I don't know exactly what I did to get things working but I think I got things working after resetting all of the nodes, I think I had just messed up the configuration of one (or possibly multiple) of them or something, thank you for your time and your extremely rapid response and helpful support!
