### ISSUE TITLE
Packages in Lima not updating. No free space

### ISSUE THREAD

**Issue by carlosrbcunha** [drandyhaas/haasmesh#5]
Hi all,

First of all, thanks for this project. It's working and it has gave me the option to use my luma system again.
I cannot update anything from within the luci interface. Also the system is informing that I have 0 bytes left to use. Is this normal? How can I update and install packages?

**Comment by drandyhaas** [comment]
You must have already installed too many additional packages? With reset to initial config, it has about 60 MB free, I think.

**Comment by carlosrbcunha** [comment]
I have not installed any. This is the same image you provided me in the beginning ! Can you point me to the latest release if possible?  Thanks.

**Comment by drandyhaas** [comment]
Very weird. You can try (from the monitor page):
"Update these scripts from github"
and then
"Update the firmware from dropbox"
