### ISSUE TITLE
Linksys EA8300 flashing fail..

### ISSUE THREAD

**Issue by skaggies** [drandyhaas/haasmesh#9]
I purchased three TP Archer C7's from Crowd Supply over a year ago, all working great and very pleased with them until two months ago when the furthest node got physically damaged and no longer works.

I cant buy the Archer C7 from Crowd Supply as no longer available and the Tri-band node I cant purchase either as it cant be shipped to EU as it has no CE mark (I am in the UK). I also looked on ebay but the prices are quite high shipped from the US so I bought a Linksys EA8300 to try and configure myself.

I managed to get OpenWRT installed and working but I am having great difficulty in getting haasmesh added to the build, specifically the 'make defconfig' command. I've spent countless hours reading, learning etc but I cant get my head around to making it work. 

My question is, would you be willing to share the Maxwell factory image for a fresh install on the EA8300 ?

Many thanks anyway for an amazing bit of software....

**Comment by drandyhaas** [comment]
Here's the factory image...
https://www.dropbox.com/s/6p7vdv80144p8i6/openwrt-ipq40xx-generic-linksys_ea8300-squashfs-factory.bin?dl=0

**Comment by galalmounir** [comment]
Related to this, I am trying to build a new OpenWRT image with the HaasMesh for the EA8300. Do you have any instructions/documentation to perform this? 

I cant find the difconfig file for the 8300 in the repo.

**Comment by drandyhaas** [comment]
That node took quite a bit of custom work to support a couple years ago, but these days works out of the box in v22, theoretically....
https://openwrt.org/toh/linksys/ea8300

**Comment by galalmounir** [comment]
Ah! That's interesting, thanks for the link! I'll give it a try and report back for future reference.

**Comment by galalmounir** [comment]
I was able to get it working using the following steps:

1. Clone the OpenWRT repository using the `v22.03.2` tag. 
2. Run update and install for the feeds
3. Clone the haasmesh repository using latest master
4. Created a blank `.config` file with the parameters below
5. Executed the `setupnodebuild.sh` script with `ea8300`
6. Executed the `make defconfig` to apply and generate remaining config options
7. Built the image using `RUN make -j $(($(nproc)+1)) V=sc download world` 

I was able to get the following parameters using `make menuconfig` and from the fork available [here](https://github.com/ContrarianReefkeeper/haasmesh.git). Added the following in the `.config` file.

```
CONFIG_TARGET_ipq40xx=y
CONFIG_TARGET_ipq40xx_generic=y
CONFIG_TARGET_ipq40xx_generic_DEVICE_linksys_ea8300=y
CONFIG_ALFRED_NEEDS_lua=y
CONFIG_BATMAN_ADV_BATMAN_V=y
CONFIG_BATMAN_ADV_BLA=y
CONFIG_BATMAN_ADV_DAT=y
CONFIG_BATMAN_ADV_DEBUG=y
CONFIG_BATMAN_ADV_MCAST=y
CONFIG_BATMAN_ADV_NC=y
CONFIG_BATMAN_ADV_TRACING=y
CONFIG_KERNEL_DYNAMIC_FTRACE=y
CONFIG_KERNEL_ENABLE_DEFAULT_TRACERS=y
CONFIG_KERNEL_FTRACE=y
CONFIG_KERNEL_FUNCTION_GRAPH_TRACER=y
CONFIG_KERNEL_FUNCTION_PROFILER=y
CONFIG_KERNEL_FUNCTION_TRACER=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENVPN_openssl_ENABLE_DEF_AUTH=y
CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
CONFIG_OPENVPN_openssl_ENABLE_LZO=y
CONFIG_OPENVPN_openssl_ENABLE_MULTIHOME=y
CONFIG_OPENVPN_openssl_ENABLE_PF=y
CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
CONFIG_PACKAGE_ALFRED_BATHOSTS=y
CONFIG_PACKAGE_ALFRED_VIS=y
CONFIG_PACKAGE_alfred=y
CONFIG_PACKAGE_banip=y
CONFIG_PACKAGE_batctl-full=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_diffutils=y
CONFIG_PACKAGE_ip-tiny=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_ipset=y
CONFIG_PACKAGE_kmod-batman-adv=y
CONFIG_PACKAGE_kmod-crypto-crc32c=y
CONFIG_PACKAGE_kmod-ipt-ipset=y
CONFIG_PACKAGE_kmod-lib-crc16=y
CONFIG_PACKAGE_kmod-lib-crc32c=y
CONFIG_PACKAGE_kmod-nfnetlink=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_libipset=y
CONFIG_PACKAGE_libiwinfo-lua=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblzo=y
CONFIG_PACKAGE_libmnl=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libpcre=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-banip=y
CONFIG_PACKAGE_luci-app-commands=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_nano=y
CONFIG_PACKAGE_openssh-client=y
CONFIG_PACKAGE_openssh-client-utils=y
CONFIG_PACKAGE_openssh-keygen=y
CONFIG_PACKAGE_openvpn-openssl=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_wget-ssl=y
CONFIG_PACKAGE_wpad-basic-wolfssl=m
CONFIG_PACKAGE_wpad-mesh-openssl=y
CONFIG_PACKAGE_zlib=y
```

**Comment by galalmounir** [comment]
I've created an image builder using a docker container. The repository can be found [here](https://github.com/galalmounir/openwrt-image-builder). 

By default, it builds images for the `EA8300`.

**Comment by skaggies** [comment]
Just a follow up, I used the supplied image and flashed my Linksys and it all works, thanks again !

Just be careful that you don't overwrite the stock firmware on the first partition, and install the firmware on the second.

But, my Linksys router is not a EA8300 as advertised on eBay when I bought it, its a MR8300. No idea how I missed that as its clearly written on the underside ! I believe the only difference to a EA8300 is that is has double the RAM. 

Nevertheless, thanks again drandyhaas for the excellent work...

**Comment by lanceberc** [comment]
I bought a Linksys EA8300 and a MR8300, built from scratch using @galalmounir 's configuration, and after a few tries was able to get meshing. There were a few issues at first possibly because I ran with only the router node for a few days before the second unit showed up.

However I get this message every 10 seconds in the log - any idea what's up?
`Fri Jan 13 00:59:36 2023 kern.warn kernel: [ 1894.873511] br-lan: received packet on bat0 with own address as source address (addr:e8:9f:80:a3:f9:89, vlan:0)`
`Fri Jan 13 00:59:46 2023 kern.warn kernel: [ 1905.113701] br-lan: received packet on bat0 with own address as source address (addr:e8:9f:80:a3:f9:89, vlan:0)`
`Fri Jan 13 00:59:57 2023 kern.warn kernel: [ 1915.353401] br-lan: received packet on bat0 with own address as source address (addr:e8:9f:80:a3:f9:89, vlan:0)`

**Comment by drandyhaas** [comment]
Sometimes two interfaces can get the same Mac address. It's harmless i think, but this should fix it...

batethmac=`ifconfig | grep HW | grep \`uci get network.bat_eth.ifname\` |cut -d ":" -f 3-|sed 's% %%g'`
uci set network.bat_eth.macaddr="00:${batethmac}"
uci changes
uci commit
/etc/init.d/network reload

**Comment by lanceberc** [comment]
Hmm... don't think that's the problem, was getting those messages even with only the router node. Currently:

Node1:
`root@192.168.2.1 ~ $ uci show network | grep bat_eth'`
`network.bat_eth=interface`
`network.bat_eth.mtu='1600'`
`network.bat_eth.proto='batadv_hardif'`
`network.bat_eth.master='bat0'`
`network.bat_eth.device='eth0.102'`
`network.bat_eth.macaddr='00:D2:A5:51:55:0A`

Node2:
`root@192.168.2.2 ~ $ uci show network | grep bat_eth`
`network.bat_eth=interface`
`network.bat_eth.mtu='1600'`
`network.bat_eth.proto='batadv_hardif'`
`network.bat_eth.master='bat0'`
`network.bat_eth.ifname='eth0.102'`
`network.bat_eth.macaddr='00:9F:80:AE:40:65'`

**Comment by drandyhaas** [comment]
No, the bat_eth interface likely has the same mac address as another interface on the _same_ node.

**Comment by lanceberc** [comment]
Maybe `br-lan` shouldn't have the same mac as `eth0`?

`root@192.168.2.1 ~ $ ifconfig | grep HW`
`bat0      Link encap:Ethernet  HWaddr 3A:DC:7A:B3:81:88`
`br-lan    Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:89`
`eth0      Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:89`
`eth0.101  Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:89`
`eth0.102  Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:89`
`eth1      Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:8A`
`mesh0     Link encap:Ethernet  HWaddr EA:9F:80:A3:F9:8D`
`wlan0-1   Link encap:Ethernet  HWaddr EE:9F:80:A3:F9:8D`
`wlan1     Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:8B`
`wlan2     Link encap:Ethernet  HWaddr E8:9F:80:A3:F9:8C`

**Comment by drandyhaas** [comment]
Right.
